{
      'name': 'Generative NEON Lines  #' + str(i),
      'description': 'Unique set of Lines Generated by AI',
      'file_url': 'ipfs://NewUriToReplace/' + str(i) + '.png',
      'attributes': [ { 'trait_type': 'Background', 'value': 'Generative Art ' } ],
      'custom_fields': {
        'edition': 5,
        'date': 1645546135037,
        'compiler': 'Atomic Labs Engine'
        }
    }
